### ISSUE TITLE
Enhancement request: Allow switching to tab

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [JessFairbairn/tab_kraken#7]
There are times when I have reasons to order/re-order tabs for the purpose of grouping related tabs on a topic I'm researching. In these cases, I don't want to sort tabs by URL, they need to stay where they are. Tab Kraken's grouping by domain is perfect for my work flow, but it would help a lot if I could have the option to switch to a tab from Tab Kraken's dropdown list in addition to the ability to close the tab.

Would this be possible?

**Comment by JessFairbairn** [comment]
This is implemented in version 0.2.4

**Comment by UNIVAC-Colonel-Panic** [comment]
works great, thank you!
